- name: restart schema-registry
  systemd:
    name: "{{schemaregistry.service_name}}"
    state: restarted
    daemon_reload: yes

- name: wait for service restart
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ schemaregistry.port }}"
    timeout: 300
    delay: 10
