Vagrant.configure(2) do |config|
  config.vm.define "kafka-node1" do |kafkanode1|
    kafkanode1.vm.box = "centos/7"
    kafkanode1.vm.hostname = "node1"
    kafkanode1.vm.network "private_network", ip: "192.168.50.21"
    kafkanode1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end
  config.vm.define "kafka-node2" do |kafkanode2|
    kafkanode2.vm.box = "centos/7"
    kafkanode2.vm.hostname = "node2"
    kafkanode2.vm.network "private_network", ip: "192.168.50.22"
    kafkanode2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end
  config.vm.define "kafka-node3" do |kafkanode3|
    kafkanode2.vm.box = "centos/7"
    kafkanode2.vm.hostname = "node3"
    kafkanode2.vm.network "private_network", ip: "192.168.50.23"
    kafkanode2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end
  config.vm.define "kafka-node4" do |kafkanode4|
    kafkanode3.vm.box = "centos/7"
    kafkanode3.vm.hostname = "node4"
    kafkanode3.vm.network "private_network", ip: "192.168.50.24"
    kafkanode3.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
      vb.cpus = "2"
    end
  end
end
