- name: restart kafka
  systemd:
    name: "{{kafkabroker.service_name}}"
    state: restarted
    daemon_reload: yes

- name: wait for service restart
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ kafkabroker.port_plaintext }}"
    timeout: 300
    delay: 10
